# ansible-task: false
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: REPO_URL
      type: string
  steps:
    - name: clone
      image: ubuntu
      script: |
        #!/bin/bash
        git clone $(params.REPO_URL) /workspace/source
        cd /workspace/source
        npm install
        npm test